baseURL = 'https://blog.kgb33.dev'
languageCode = 'en-us'
title = ""
theme = "gruvbox"

[build]
  # The theme enables writeStats which is required for PurgeCSS
  _merge = "deep"

# See: https://github.com/schnerring/hugo-theme-gruvbox/issues/16
[module]
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-github-readme-stats"
  [[module.imports]]
    path = "github.com/schnerring/hugo-mod-json-resume"
    [[module.imports.mounts]]
      source = "data"
      target = "data"
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "assets/css/json-resume.css"
      target = "assets/css/critical/44-json-resume.css"
  [[module.mounts]]
    # required by hugo-mod-json-resume
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/prism-themes/themes"
    target = "assets/prism-themes"
  [[module.mounts]]
    source = "node_modules/typeface-fira-code/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/typeface-roboto-slab/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # used for in-line prismjs

[params]
  avatar = "/images/avatar.jpg"
  author = "Kelton Bassingthwaite"
  description = "Change config.toml -> [params] -> description to update this"
  subtitle = ""
  defaultTheme = "dark"
  themeColor = "green"

	[params.logo]
	  text = "reader@blog"

	[[params.social]]
  	  icon = "github"
      name = "Github"
      url = "https://github.com/KGB33"

	[params.prism]
	  # https://prismjs.com/#supported-languages
	  languages = [
        "markup",
        "css",
        "clike",
        "javascript",
        "bash",
        "diff",
        "toml",
		"python",
		"sql"
      ]
      plugins = [
        "normalize-whitespace",
        "toolbar",
        "copy-to-clipboard",
        "line-numbers",
        "command-line",
        "diff-highlight"
      ]

[menu]
	[[menu.main]]
	identifier = "posts"
	name = "Posts"
	url = "/"
	weight = 10

	[[menu.main]]
	identifier = "notes"
	name = "Notes"
	url = "/notes/"
	weight = 20

	[[menu.main]]
	identifier = "projects"
	name = "Projects"
	url = "https://github.com/KGB33"
	weight = 30
