baseURL = 'https://blog.kgb33.dev'
languageCode = 'en-us'
title = ""
theme = "m10c"

[params]
	avatar = "/images/avatar.jpg"
	author = "Kelton Bassingthwaite"

[[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/KGB33"

# Gruvbox Green Colors
[params.style]
  darkestColor = "#1d2021"
  darkColor = "#282828"
  lightColor = "#a89984"
  lightestColor = "#ebdbb2"
  primaryColor = "#98971a"
