name: "Build & Push Container Image"

# Only a single job with this concurrency can run at any given time
concurrency: release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
permissions:
  packages: write
  actions: write
jobs:
  publish:
    name: "Build & Push to GHCR"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0
      - name: Restore container cache
        id: cache
        uses: actions/cache@v5
        with:
          path: /tmp/dagger-engine.tar.gz
          key: dagger-engine-${{ hashFiles('dagger.json') }}
          restore-keys: dagger-engine-
      - name: Load cached image
        if: steps.cache.outputs.cache-hit == 'true'
        run: gunzip -c /tmp/dagger-engine.tar.gz | docker load
      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.20.8 sh; cd -; }
      - name: Run Dagger pipeline
        run: dagger call publish --token env://GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
      - name: Cache dagger engine
        run: docker save registry.dagger.io/engine:v0.20.8 | gzip > /tmp/dagger-engine.tar.gz
