name: "Build & Push Container Image"

# Only a single job with this concurrency can run at any given time
concurrency: release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
permissions:
  packages: write
  actions: write
jobs:
  publish:
    name: "Build & Push to GHCR"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Callout to dagger"
        uses: dagger/dagger-for-github@v3
        env:
          GHCR_PAT: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Use buildkit's gha cache support
          # Watch https://github.com/dagger/dagger-for-github/issues/39
          # for cache support being built-into the dagger-action
          cmds: |
            project init
            project update
            do --cache-from type=gha --cache-to type=gha build
            do --cache-from type=gha --cache-to type=gha publish
