name: "Build & Push Container Image"

# Only a single job with this concurrency can run at any given time
concurrency: release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
permissions:
  packages: write
  actions: write
jobs:
  publish:
    name: "Build & Push to GHCR"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Dagger CLI
        run: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=0.15.4 sh; cd -; }
      - name: Run Dagger pipeline
        run: dagger call --mod ci/ publish --dir . --token cmd:'echo -n ${{ secrets.GITHUB_TOKEN }}'
